## Build settings
gems: [jekyll-babel]
exclude: [_source/_assets]
source: _source
destination: _dist
# highlighter: pygments
markdown: kramdown
# theme: minima
port: 3000
safe: true

## Assets compilers

sass:
  style: compressed

babel_js_options:
  compact: true
  comments: false

## Basic
title: Arthur Vasconcelos
author: Chris Turner
email: vasconcelos.arthur@gmail.com
description: Personal blog and resume
baseurl: "/"
url: ""

## Social
github: arthurvasconcelos # https://github.com/{user}
stackoverflow: 3130385/arthur-vasconcelos # http://stackoverflow.com/users/{user}
facebook: vasconcelos.arthur # https://www.facebook.com/{user}
twitter: jookeringa # https://twitter.com/{user}
linkedin: arthurvasconcelos # https://linkedin.com/in/{user}

## Services
disqus: jookeringa
google_analytics: UA-28901644-2
